export type ConfigToken = {
  /** Token generated by Paperless */
  token: string;
  username?: undefined;
  password?: undefined;
};

export type ConfigUsernamePassword = {
  /** Username you use to login to the Dashboard */
  username: string;
  /** Password you use to login to the Dashboard */
  password: string;
  token?: undefined;
};

export type ConfigBase = {
  /** Protocol and Address of your Paperless Instance */
  host: string;
  /** Port of your Paperless Instance */
  port?: number | string;
  /** Ignore SSL Errors */
  ignoreSSL?: boolean;
};

export type Config = ConfigBase & (ConfigUsernamePassword | ConfigToken);
